version: '3.1'

services:

  redis:
    image: redis:latest
    container_name: rd01

  celery_worker:
    build: ./
    command: celery -A api_test worker -l info
    depends_on:
      - "redis"
    restart: always

  celery_beat:
    build: ./
    command: celery -A api_test beat -l info
    depends_on:
      - "redis"
    restart: always

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/db_data:/var/lib/postgresql/data

  migration:
    image: api
    command: bash -c "python manage.py makemigrations api_test_work && python manage.py migrate"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  test_api:
    image: api
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
#    command: uwsgi --http-socket :8000 --py-autoreload 1 --module api_test.wsgi:application
    restart: always
    volumes:
      - .:/api_test
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - redis